name: ES4X Site

on:
  push:
    branches:
      - develop

jobs:
  build_site:
    name: "Build site with vuepress"
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - name: "Install vuepress"
        run: npm install
      - name: "Build vuepress"
        run: "$(npm bin)/vuepress build docs"
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
